### ISSUE TITLE
Twilio: invalid from doesnt return error

### ISSUE THREAD

**Issue by timmyg** [VennHQ/venn-messaging-node#32]
If you use an invalid from number (an 11 digit number that isnt a valid twilio from number for your account), it return an empty success object.

We need to see what error twilio returns when this happens and return that error to the customer.

**Comment by GnashCraft** [comment]
Updated the Twilio handler to handle this error. It logs it into the sendLog, but probably still returns an undefined result. I think the return of an undefined result is a separate issue, and I have a fix for that as well, but I'd to discuss it with you in more detail.
